--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "zhCN");
if ( not L ) then 
    return;
end

-- GuildBank
--Translation missing 
L["ARMORY_CMD_DELETE_GUILD"] = "gb"
--Translation missing 
L["ARMORY_CMD_DELETE_GUILD_MSG"] = "Guild bank of '%1$s' in realm '%2$s' has been removed."
--Translation missing 
L["ARMORY_CMD_DELETE_GUILD_NOT_FOUND"] = "Guild bank of '%1$s' in realm '%2$s' not found!"
--Translation missing 
L["ARMORY_CMD_DELETE_GUILD_PARAMS_TEXT"] = "[guild] [realm]"
--Translation missing 
L["ARMORY_CMD_DELETE_GUILD_TEXT"] = "delete guild bank"
--Translation missing 
L["ARMORY_CMD_GUILDBANK"] = "guildbank|gb"
L["ARMORY_CMD_GUILDBANK_MENUTEXT"] = "开关Guild Bank"
L["ARMORY_CMD_GUILDBANK_TEXT"] = "开关Guild Bank"
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTALL_MENUTEXT"] = "Include all realms in counts"
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTALL_TEXT"] = "include item counts for all realms"
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTALL_TOOLTIP"] = "If enabled, Guild Bank totals are shown for all realms; otherwise only for the current realm."
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_MENUTEXT"] = "Include current guild only"
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TEXT"] = "include item counts for the current guild only"
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TOOLTIP"] = "If enabled, Guild Bank totals are shown for the current and selected character's guild only."
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTPGB_MENUTEXT"] = "Include personal guilds only"
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTPGB_TEXT"] = "include item counts for personal guilds only"
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTPGB_TOOLTIP"] = "If enabled, Guild Banks totals are shown for personal guilds only."
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_MENUTEXT"] = "Include all factions in counts"
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TEXT"] = "include item counts for all factions"
--Translation missing 
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TOOLTIP"] = "If enabled, Guild Bank totals are shown for all factions; otherwise only for the current faction."
L["ARMORY_CMD_SET_AGBFIND_MENUTEXT"] = "包含在 '/ar find item|all'"
L["ARMORY_CMD_SET_AGBFIND_TEXT"] = "搜索物品时包含在内"
L["ARMORY_CMD_SET_AGBFIND_TOOLTIP"] = "如果打开此功能, 当使用 '/ar find item|all' 命令搜索数据库时将包含公会银行."
--Translation missing 
L["ARMORY_CMD_SET_AGBINTEGRATE_MENUTEXT"] = "Integrate with inventory"
--Translation missing 
L["ARMORY_CMD_SET_AGBINTEGRATE_TEXT"] = "integrate with Armory's inventory"
--Translation missing 
L["ARMORY_CMD_SET_AGBINTEGRATE_TOOLTIP"] = "If enabled, the selected character's Guild Bank will be added as an extra tab in the inventory sheet."
L["ARMORY_CMD_SET_AGBITEMCOUNT_MENUTEXT"] = "在信息提示中显示物品数量"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TEXT"] = "在信息提示中显示物品数量"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TOOLTIP"] = "如果打开此功能, 物品提示信息中将显示在公会银行中的数量."
L["ARMORY_CMD_SET_AGBUNICOLOR_MENUTEXT"] = "使用 Armory 的颜色"
L["ARMORY_CMD_SET_AGBUNICOLOR_TEXT"] = "链接到 Armory 的物品数字颜色"
L["ARMORY_CMD_SET_AGBUNICOLOR_TOOLTIP"] = "I如果打开此功能, 所有物品数量使用同一个颜色."
L["ARMORY_GUILDBANK_ABORTING"] = "中断..."
L["ARMORY_GUILDBANK_NO_DATA"] = "没有可用的公会银行数据."
L["ARMORY_GUILDBANK_NO_TABS"] = "请查看银行并打开所有标签..."
L["ARMORY_GUILDBANK_SUBTEXT"] = "设置Armory Guild Bank"
L["ARMORY_GUILDBANK_TITLE"] = "公会银行"
--Translation missing 
L["ARMORY_PERSONAL"] = "Personal"
--Translation missing 
L["ARMORY_PERSONAL_GUILDBANK"] = "Personal Guild Bank"
--Translation missing 
L["ARMORY_PERSONAL_GUILDBANK_TOOLTIP"] = "If enabled, guild bank gold will be included in character gold totals."
L["BINDING_NAME_ARMORYGUILDBANK_TOGGLE"] = "开关Armory Guild Bank"

