if GetLocale() == "koKR" then
qcLocalize = {
	ABYSSALDEPTHS = "??? ??", -- Needs review
	AHNKAHETTHEOLDKINGDOM = "????: ?? ??",
	AHNQIRAJ = "????",
	AHNQIRAJTHEFALLENKINGDOM = "????: ??? ??", -- Needs review
	ALCHEMY = "???", -- Needs review
	ALTERACVALLEY = "??? ??",
	ARATHIBASIN = "??? ??",
	ARATHIHIGHLANDS = "??? ??", -- Needs review
	ARCHAEOLOGY = "???", -- Needs review
	ASHENVALE = "?? ???", -- Needs review
	ASHRAN = "Ashran", -- Requires localization
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AUCHENAICRYPTS = "???? ???",
	AUCHINDOUN = "???",
	AZEROTH = "Azeroth", -- Requires localization
	AZJOLNERUB = "????",
	AZSHARA = "????", -- Needs review
	AZUREMYSTISLE = "???? ?", -- Needs review
	BADLANDS = "??? ?", -- Needs review
	BARADINHOLD = "??? ??",
	BATTLEGROUNDS = "??", -- Needs review
	BATTLEPETS = "?? ?", -- Needs review
	BLACKFATHOMDEEPS = "???? ??",
	BLACKROCKCAVERNS = "???? ??",
	BLACKROCKDEPTHS = "???? ??",
	BLACKROCKFOUNDRY = "Blackrock Foundry", -- Requires localization
	BLACKROCKSPIRE = "???? ??",
	BLACKSMITHING = "????", -- Needs review
	BLACKTEMPLE = "?? ??",
	BLACKWINGDESCENT = "???? ???",
	BLACKWINGLAIR = "???? ??",
	BLADESEDGEMOUNTAINS = "?? ??", -- Needs review
	BLASTEDLANDS = "???? ?", -- Needs review
	BLOODMAULSLAGMINES = "Bloodmaul Slag Mines", -- Requires localization
	BLOODMYSTISLE = "???? ?", -- Needs review
	BOREANTUNDRA = "??? ?", -- Needs review
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "?? ??", -- Needs review
	BREWMOONFESTIVAL = "Brewmoon Festival", -- Requires localization
	BURNINGSTEPPES = "??? ??", -- Needs review
	CAVERNSOFTIME = "??? ??",
	CENTRALKALIMDOR = "Central Kalimdor", -- Requires localization
	CHILDRENSWEEK = "??? ??", -- Needs review
	CLASSES = "??", -- Needs review
	CLASSQUESTS = "?? ???", -- Needs review
	CLEARUPDATECACHE = "???? ?? ???", -- Needs review
	COILFANGRESERVOIR = "????? ???", -- Needs review
	COMBINEDMAPANDQUESTFILTERS = "?? ??? ?? ?? ??", -- Needs review
	CONFIGSUBTITLE = "Quest Completist?? ?? ??? ??? ??? ??? ??? ? ? ????.", -- Needs review
	CONFIGTITLE = "Quest Completist - ??", -- Needs review
	CONTINENTS = "??", -- Needs review
	COOKING = "??", -- Needs review
	CRYSTALSONGFOREST = "???? ?", -- Needs review
	DALARAN = "???", -- Needs review
	DARKMOONFAIRE = "??? ??", -- Needs review
	DARKSHORE = "????", -- Needs review
	DARNASSUS = "?????", -- Needs review
	DAYOFTHEDEAD = "??? ?", -- Needs review
	DEADWINDPASS = "???? ??", -- Needs review
	DEATHKNIGHT = "??? ??", -- Needs review
	DEEPHOLM = "??? ??", -- Needs review
	DEEPRUNTRAM = "??? ???", -- Needs review
	DESOLACE = "??? ?", -- Needs review
	DIREMAUL = "??? ??",
	DRAENOR = "Draenor", -- Requires localization
	DRAGONBLIGHT = "?? ???", -- Needs review
	DRAGONSOUL = "?? ??",
	DRAKTHARONKEEP = "???? ??",
	DREADWASTES = "??? ???", -- Needs review
	DRUID = "????", -- Needs review
	DUNGEONSANDRAIDS = "?? & ???", -- Needs review
	DUNMOROGH = "? ??", -- Needs review
	DUROTAR = "???", -- Needs review
	DUSKWOOD = "???", -- Needs review
	DUSTWALLOWMARSH = "???? ???", -- Needs review
	EASTERNKINGDOMS = "?? ??", -- Needs review
	EASTERNPLAGUELANDS = "?? ????", -- Needs review
	ELEMENTALBONDS = "Elemental Bonds", -- Requires localization
	ELWYNNFOREST = "?? ?", -- Needs review
	ENCHANTING = "????", -- Needs review
	ENDTIME = "??? ?",
	ENGINEERING = "????", -- Needs review
	EVERSONGWOODS = "???? ?", -- Needs review
	EYEOFTHESTORM = "??? ?",
	FELWOOD = "???", -- Needs review
	FERALAS = "????", -- Needs review
	FIRELANDS = "?? ?",
	FIRELANDSINVASION = "Firelands Invasion", -- Requires localization
	FIRSTAID = "????", -- Needs review
	FISHING = "??", -- Needs review
	FROSTFIRERIDGE = "Frostfire Ridge", -- Requires localization
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GATEOFTHESETTINGSUN = "Gate of the Setting Sun", -- Requires localization
	GHOSTLANDS = "??? ?", -- Needs review
	GILNEAS = "????",
	GILNEASCITY = "???? ?",
	GNOMEREGAN = "???",
	GORGROND = "Gorgrond", -- Requires localization
	GREENSTONEVILLAGE = "Greenstone Village", -- Requires localization
	GRIMBATOL = "?? ??",
	GRIMRAILDEPOT = "Grimrail Depot", -- Requires localization
	GRIZZLYHILLS = "?? ???", -- Needs review
	GRUULSLAIR = "??? ??",
	GUNDRAK = "???",
	HALLOWSEND = "??? ??", -- Needs review
	HALLSOFLIGHTNING = "??? ??",
	HALLSOFORIGINATION = "??? ??",
	HALLSOFREFLECTION = "??? ??",
	HALLSOFSTONE = "?? ??",
	HARVESTFESTIVAL = "?? ??", -- Needs review
	HELLFIRECITADEL = "??? ??", -- Needs review
	HELLFIREPENINSULA = "??? ??", -- Needs review
	HELLFIRERAMPARTS = "??? ??",
	HERBALISM = "????", -- Needs review
	HIDECOMPLETEDQUESTS = "??? ??? ??", -- Needs review
	HIDEINPROGRESSQUESTS = "???? ??? ??", -- Needs review
	HIDELOWLEVELQUESTS = "??? ??? ??", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "????? ?? ?? ?? ??? ??", -- Needs review
	HIDEOTHERFACTIONQUESTS = "???? ??? ??", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "?? ???? ??? ??", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "?? ?? ? ?? ??? ??", -- Needs review
	HIGHMAUL = "Highmaul", -- Requires localization
	HILLSBRADFOOTHILLS = "???? ???", -- Needs review
	HOUROFTWILIGHT = "??? ??",
	HOWLINGFJORD = "???? ??", -- Needs review
	HROTHGARSLANDING = "????? ???", -- Needs review
	HUNTER = "???", -- Needs review
	HYJALSUMMIT = "??? ??",
	ICECROWN = "????", -- Needs review
	ICECROWNCITADEL = "???? ??",
	INSCRIPTION = "????", -- Needs review
	IRONDOCKS = "Iron Docks", -- Requires localization
	IRONFORGE = "?????", -- Needs review
	ISLEOFCONQUEST = "??? ?",
	ISLEOFGIANTS = "Isle of Giants", -- Requires localization
	ISLEOFQUELDANAS = "????? ?", -- Needs review
	ISLEOFTHUNDER = "Isle of Thunder", -- Requires localization
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "????", -- Needs review
	KALIMDOR = "????", -- Needs review
	KARAZHAN = "???",
	KELPTHARFOREST = "???? ?", -- Needs review
	KEZAN = "??", -- Needs review
	KHAZMODAN = "Khaz Modan", -- Requires localization
	KRASARANGWILDS = "???? ??",
	KUNLAISUMMIT = "??? ???",
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "????", -- Needs review
	LEGENDARY = "??", -- Needs review
	LOCHMODAN = "?? ??",
	LORDAERON = "Lordaeron", -- Requires localization
	LOSTCITYOFTHETOLVIR = "???? ???? ??",
	LOVEISINTHEAIR = "???? ???", -- Needs review
	LUNARFESTIVAL = "?? ??", -- Needs review
	MAGE = "???", -- Needs review
	MAGISTERSTERRACE = "????? ??",
	MAGTHERIDONSLAIR = "?????? ??",
	MANATOMBS = "?? ??",
	MAPFILTERS = "? ??", -- Needs review
	MARAUDON = "????",
	MIDSUMMERFIREFESTIVAL = "??? ?? ??", -- Needs review
	MINING = "??", -- Needs review
	MISCELLANEOUS = "??", -- Needs review
	MOGUSHANPALACE = "Mogu'shan Palace", -- Requires localization
	MOGUSHANVAULTS = "??? ??",
	MOLTENCORE = "?? ???",
	MOLTENFRONT = "???? ???",
	MONK = "???", -- Needs review
	MOONGLADE = "??", -- Needs review
	MOUNTHYJAL = "??? ?", -- Needs review
	MULGORE = "???", -- Needs review
	NAGRAND = "????",
	NAXXRAMAS = "?????",
	NETHERSTORM = "??? ??",
	NEWYEARSEVE = "New Year's Eve", -- Requires localization
	NOBLEGARDEN = "??? ??", -- Needs review
	NORTHERNBARRENS = "?? ??? ?", -- Needs review
	NORTHERNKALIMDOR = "Northern Kalimdor", -- Requires localization
	NORTHERNSTRANGLETHORN = "?? ????", -- Needs review
	NORTHREND = "????", -- Needs review
	OLDHILLSBRADFOOTHILLS = "? ???? ???",
	ONYXIASLAIR = "????? ??",
	OPTIONS = "??", -- Needs review
	ORGRIMMAR = "????", -- Needs review
	OUTLAND = "????", -- Needs review
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "???", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "????", -- Needs review
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "?? ??? ?????...", -- Needs review
	PILGRIMSBOUNTY = "Pilgrim's Bounty", -- Requires localization
	PITOFSARON = "??? ???",
	PRIEST = "??", -- Needs review
	PROFESSIONS = "????", -- Needs review
	PROVINGGROUNDS = "Proving Grounds", -- Requires localization
	QUERYREQUESTED = "?? ??? ??????...", -- Needs review
	QUESTLISTFILTERS = "??? ?? ??", -- Needs review
	QUESTSFOUND = "%d ??? ??", -- Needs review
	RAGEFIRECHASM = "???? ??",
	RAIDS = "???", -- Needs review
	RAZORFENDOWNS = "???? ??",
	RAZORFENKRAUL = "???? ??",
	REDRIDGEMOUNTAINS = "???? ??",
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "??", -- Needs review
	RUINSOFAHNQIRAJ = "???? ??",
	RUINSOFGILNEAS = "???? ??",
	RUINSOFGILNEASCITY = "???? ? ??",
	SCARLETHALLS = "Scarlet Halls", -- Requires localization
	SCARLETMONASTERY = "????? ???",
	SCENARIO = "Scenario", -- Requires localization
	SCHOLOMANCE = "?????",
	SEARINGGORGE = "????? ??",
	SEASONAL = "?? ??", -- Needs review
	SERPENTSHRINECAVERN = "?? ??",
	SETHEKKHALLS = "??? ??",
	SHADOPANMONASTERY = "??? ???", -- Needs review
	SHADOWFANGKEEP = "?????? ??",
	SHADOWLABYRINTH = "??? ??",
	SHADOWMOONBURIALGROUNDS = "Shadowmoon Burial Grounds", -- Requires localization
	SHADOWMOONVALLEY = "??? ???",
	SHAMAN = "???", -- Needs review
	SHATTRATHCITY = "????",
	SHIMMERINGEXPANSE = "??? ??", -- Needs review
	SHOLAZARBASIN = "???? ??",
	SHOWMAPICONS = "?? ??? ??", -- Needs review
	SIEGEOFNIUZAOTEMPLE = "???? ?? ??",
	SIEGEOFORGRIMMAR = "Siege of Orgrimmar", -- Requires localization
	SILITHUS = "????", -- Needs review
	SILVERMOONCITY = "???",
	SILVERPINEFOREST = "????? ?",
	SILVERSHARDMINES = "???? ??", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "???", -- Needs review
	SKYREACH = "Skyreach", -- Requires localization
	SORTALPHA = "?? : ??? ?", -- Needs review
	SORTLEVEL = "?? : ?? ?", -- Needs review
	SOUTHERNBARRENS = "?? ??? ?", -- Needs review
	SOUTHERNKALIMDOR = "Southern Kalimdor", -- Requires localization
	SPECIAL = "??", -- Needs review
	SPECIALS = "??", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	SPIRESOFARAK = "Spires Of Arak", -- Requires localization
	STONETALONMOUNTAINS = "??? ??", -- Needs review
	STORMSHIELD = "Stormshield", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STORMSTOUTBREWERY = "?????? ???",
	STORMWINDCITY = "????",
	STRANDOFTHEANCIENTS = "??? ??",
	STRANGLETHORNVALE = "???? ???",
	STRATHOLME = "?????",
	SUNKENTEMPLE = "???? ??",
	SUNSTRIDERISLE = "Sunstrider Isle", -- Requires localization
	SUNWELLPLATEAU = "??? ??",
	SWAMPOFSORROWS = "??? ?",
	TAILORING = "???", -- Needs review
	TALADOR = "Talador", -- Requires localization
	TANAANJUNGLE = "Tanaan Jungle", -- Requires localization
	TANARIS = "????", -- Needs review
	TELDRASSIL = "????", -- Needs review
	TEMPESTKEEP = "??? ??",
	TEMPLEOFAHNQIRAJ = "???? ??", -- Needs review
	TEMPLEOFKOTMOGU = "???? ??",
	TEMPLEOFTHEJADESERPENT = "Temple of the Jade Serpent", -- Requires localization
	TEMPLEOFTHEREDCRANE = "???", -- Needs review
	TEROKKARFOREST = "???? ?",
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEARCATRAZ = "?????",
	THEBASTIONOFTWILIGHT = "??? ??",
	THEBATTLEFORGILNEAS = "???? ???",
	THEBLACKMORASS = "???",
	THEBLOODFURNACE = "?? ???",
	THEBOTANICA = "??? ??",
	THECAPEOFSTRANGLETHORN = "???? ?", -- Needs review
	THECULLINGOFSTRATHOLME = "? ?????",
	THEDEADMINES = "??? ??",
	THEEVERBLOOM = "The Everbloom", -- Requires localization
	THEEXODAR = "????", -- Needs review
	THEEYE = "?", -- Needs review
	THEEYEOFETERNITY = "??? ?",
	THEFORGEOFSOULS = "??? ???",
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHALFHILLMARKET = "??? ??", -- Needs review
	THEHINTERLANDS = "?? ???",
	THEJADEFOREST = "??",
	THELOSTISLES = "???? ?",
	THEMAELSTROM = "??? ????",
	THEMECHANAR = "????",
	THENEXUS = "??? ?",
	THEOBSIDIANSANCTUM = "??? ??",
	THEOCULUS = "??? ?",
	THERUBYSANCTUM = "?? ??",
	THESHATTEREDHALLS = "???? ?? ??",
	THESLAVEPENS = "?? ???",
	THESTEAMVAULT = "?? ???",
	THESTOCKADE = "???? ????",
	THESTONECORE = "?????",
	THESTORMPEAKS = "??? ???",
	THETEMPLEOFTHEJADESERPENT = "???", -- Needs review
	THEUNDERBOG = "????",
	THEVEILEDSTAIR = "??? ??", -- Needs review
	THEVIOLETHOLD = "??? ??",
	THEVORTEXPINNACLE = "???? ??",
	THEWANDERINGISLE = "???",
	THEZANDALARI = "???", -- Needs review
	THOUSANDNEEDLES = "???? ???", -- Needs review
	THRONEOFTHEFOURWINDS = "? ??? ??",
	THRONEOFTHETIDES = "??? ??",
	THRONEOFTHUNDER = "Throne of Thunder", -- Requires localization
	THUNDERBLUFF = "?? ???", -- Needs review
	TIMELESSISLE = "Timeless Isle", -- Requires localization
	TIRISFALGLADES = "???? ?",
	TOLBARAD = "? ???",
	TOLBARADPENINSULA = "? ??? ??",
	TOURNAMENT = "????", -- Needs review
	TOWNLONGSTEPPES = "?? ??",
	TRIALOFTHECHAMPION = "??? ???",
	TRIALOFTHECRUSADER = "???? ???",
	TWILIGHTHIGHLANDS = "??? ??",
	TWINPEAKS = "??? ???",
	ULDAMAN = "???",
	ULDUAR = "????",
	ULDUM = "??", -- Needs review
	UNDERCITY = "????",
	UNGAINGOO = "Unga Ingoo", -- Requires localization
	UNGOROCRATER = "??? ???", -- Needs review
	UPPERBLACKROCKSPIRE = "Upper Blackrock Spire", -- Requires localization
	UTGARDEKEEP = "???? ??",
	UTGARDEPINNACLE = "???? ??",
	VALEOFETERNALBLOSSOMS = "??? ???",
	VALLEYOFTHEFOURWINDS = "? ??? ??",
	VASHJIR = "???",
	VAULTOFARCHAVON = "??? ??",
	WAILINGCAVERNS = "??? ??",
	WARLOCK = "????", -- Needs review
	WARRIOR = "??", -- Needs review
	WARSONGGULCH = "???? ??",
	WARSPEAR = "Warspear", -- Requires localization
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WELLOFETERNITY = "??? ?",
	WESTERNPLAGUELANDS = "?? ????",
	WESTFALL = "?? ????",
	WETLANDS = "???",
	WINTERGRASP = "????? ??",
	WINTERSPRING = "??? ??", -- Needs review
	WINTERVEIL = "???? ??", -- Needs review
	WORLDEVENTS = "?? ???", -- Needs review
	ZANGARMARSH = "??? ???",
	ZULAMAN = "???",
	ZULDRAK = "???",
	ZULFARRAK = "???",
	ZULGURUB = "???",
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "The Dreamgrove",
	AZSUNA = "Azsuna",
	HIGHMOUNTAIN = "Highmountain",
	STORMHEIM = "Stormheim",
	SURAMAR = "Suramar",
	VALSHARAH = "Val'sharah",
	DEMONHUNTER = "Demon Hunter",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Hall of the Guardian",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Netherlight Temple",
	SKYHOLD = "Skyhold",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	ACHERUSTHEEBONHOLD = "Acherus: The Ebon Hold",
	BLACKOOKHOLD = "Black Rook Hold",
	COURTOFSTARS = "Court of Stars",
	DARKHEARTTHICKET	 = "Darkheart Thicket",
	EYEOFAZSHARA = "	Eye of Azshara",
	HALLSOFVALOR = "Halls of Valor",
	MAWOFSOULS = "Maw of Souls",
	NELTHARIONSLAIR = "Neltharion's Lair",
	THEARCWAY = "The Arcway", 
	VAULTOFTHEWARDENS = "Vault of the Wardens",
	VIOLETHOLD = "Violet Hold",
	THEEMERALDNIGHTMARE = "The Emerald Nightmare",
	TRIALOFVALOR = "Trial of Valor",
	THENIGHTHOLD = "	The Nighthold",
	BROKENSHORE = "Broken Shore",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	CATHEDRALOFETERNALNIGHT = "Cathedral of Eternal Night", 
	RETURNTOKARAZHAN = "Return to Karazhan",
 	TOMBOFSARGERAS = "Tomb of Sargeras",
}

end