if GetLocale() == "zhTW" then
qcLocalize = {
	ABYSSALDEPTHS = "????",
	AHNKAHETTHEOLDKINGDOM = "????:???", -- Needs review
	AHNQIRAJ = "???", -- Needs review
	AHNQIRAJTHEFALLENKINGDOM = "???: ?????",
	ALCHEMY = "???", -- Needs review
	ALTERACVALLEY = "?????? \009", -- Needs review
	ARATHIBASIN = "?????", -- Needs review
	ARATHIHIGHLANDS = "?????",
	ARCHAEOLOGY = "???", -- Needs review
	ASHENVALE = "??",
	ASHRAN = "Ashran", -- Requires localization
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AUCHENAICRYPTS = "?????", -- Needs review
	AUCHINDOUN = "???", -- Needs review
	AZEROTH = "Azeroth", -- Requires localization
	AZJOLNERUB = "???-??", -- Needs review
	AZSHARA = "???",
	AZUREMYSTISLE = "???",
	BADLANDS = "????",
	BARADINHOLD = "????", -- Needs review
	BATTLEGROUNDS = "??", -- Needs review
	BATTLEPETS = "????", -- Needs review
	BLACKFATHOMDEEPS = "????", -- Needs review
	BLACKROCKCAVERNS = "????", -- Needs review
	BLACKROCKDEPTHS = "????", -- Needs review
	BLACKROCKFOUNDRY = "Blackrock Foundry", -- Requires localization
	BLACKROCKSPIRE = "???", -- Needs review
	BLACKSMITHING = "??", -- Needs review
	BLACKTEMPLE = "????", -- Needs review
	BLACKWINGDESCENT = "????", -- Needs review
	BLACKWINGLAIR = "????", -- Needs review
	BLADESEDGEMOUNTAINS = "????",
	BLASTEDLANDS = "????",
	BLOODMAULSLAGMINES = "Bloodmaul Slag Mines", -- Requires localization
	BLOODMYSTISLE = "???",
	BOREANTUNDRA = "????",
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "???", -- Needs review
	BREWMOONFESTIVAL = "Brewmoon Festival", -- Requires localization
	BURNINGSTEPPES = "????",
	CAVERNSOFTIME = "????", -- Needs review
	CENTRALKALIMDOR = "Central Kalimdor", -- Requires localization
	CHILDRENSWEEK = "???", -- Needs review
	CLASSES = "??", -- Needs review
	CLASSQUESTS = "????", -- Needs review
	CLEARUPDATECACHE = "??????", -- Needs review
	COILFANGRESERVOIR = "????", -- Needs review
	COMBINEDMAPANDQUESTFILTERS = "??????????????", -- Needs review
	CONFIGSUBTITLE = "????????? Quest Completist ??????????????", -- Needs review
	CONFIGTITLE = "Quest Completist - ??", -- Needs review
	CONTINENTS = "??", -- Needs review
	COOKING = "??", -- Needs review
	CRYSTALSONGFOREST = "??????",
	DALARAN = "???",
	DARKMOONFAIRE = "?????", -- Needs review
	DARKSHORE = "???",
	DARNASSUS = "????",
	DAYOFTHEDEAD = "???", -- Needs review
	DEADWINDPASS = "????",
	DEATHKNIGHT = "????", -- Needs review
	DEEPHOLM = "????",
	DEEPRUNTRAM = "????",
	DESOLACE = "????",
	DIREMAUL = "????", -- Needs review
	DRAENOR = "Draenor", -- Requires localization
	DRAGONBLIGHT = "????",
	DRAGONSOUL = "????", -- Needs review
	DRAKTHARONKEEP = "???????", -- Needs review
	DREADWASTES = "????",
	DRUID = "???", -- Needs review
	DUNGEONSANDRAIDS = "??????", -- Needs review
	DUNMOROGH = "???",
	DUROTAR = "???",
	DUSKWOOD = "????",
	DUSTWALLOWMARSH = "????",
	EASTERNKINGDOMS = "????",
	EASTERNPLAGUELANDS = "?????",
	ELEMENTALBONDS = "????", -- Needs review
	ELWYNNFOREST = "?????",
	ENCHANTING = "??", -- Needs review
	ENDTIME = "????", -- Needs review
	ENGINEERING = "???", -- Needs review
	EVERSONGWOODS = "????",
	EYEOFTHESTORM = "????", -- Needs review
	FELWOOD = "?????",
	FERALAS = "???",
	FIRELANDS = "????", -- Needs review
	FIRELANDSINVASION = "????????", -- Needs review
	FIRSTAID = "??", -- Needs review
	FISHING = "??", -- Needs review
	FROSTFIRERIDGE = "Frostfire Ridge", -- Requires localization
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GATEOFTHESETTINGSUN = "Gate of the Setting Sun", -- Requires localization
	GHOSTLANDS = "????",
	GILNEAS = "????", -- Needs review
	GILNEASCITY = "?????", -- Needs review
	GNOMEREGAN = "????", -- Needs review
	GORGROND = "Gorgrond", -- Requires localization
	GREENSTONEVILLAGE = "Greenstone Village", -- Requires localization
	GRIMBATOL = "?????", -- Needs review
	GRIMRAILDEPOT = "Grimrail Depot", -- Requires localization
	GRIZZLYHILLS = "????",
	GRUULSLAIR = "?????", -- Needs review
	GUNDRAK = "????", -- Needs review
	HALLOWSEND = "???", -- Needs review
	HALLSOFLIGHTNING = "????", -- Needs review
	HALLSOFORIGINATION = "????", -- Needs review
	HALLSOFREFLECTION = "????", -- Needs review
	HALLSOFSTONE = "????", -- Needs review
	HARVESTFESTIVAL = "???", -- Needs review
	HELLFIRECITADEL = "?????", -- Needs review
	HELLFIREPENINSULA = "?????",
	HELLFIRERAMPARTS = "?????", -- Needs review
	HERBALISM = "???", -- Needs review
	HIDECOMPLETEDQUESTS = "????????", -- Needs review
	HIDEINPROGRESSQUESTS = "????????", -- Needs review
	HIDELOWLEVELQUESTS = "????????", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "????????????", -- Needs review
	HIDEOTHERFACTIONQUESTS = "?????????", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "?????????", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "???????????", -- Needs review
	HIGHMAUL = "Highmaul", -- Requires localization
	HILLSBRADFOOTHILLS = "????????",
	HOUROFTWILIGHT = "????", -- Needs review
	HOWLINGFJORD = "????",
	HROTHGARSLANDING = "??????",
	HUNTER = "??", -- Needs review
	HYJALSUMMIT = "??????", -- Needs review
	ICECROWN = "????",
	ICECROWNCITADEL = "????", -- Needs review
	INSCRIPTION = "???", -- Needs review
	IRONDOCKS = "Iron Docks", -- Requires localization
	IRONFORGE = "???",
	ISLEOFCONQUEST = "????", -- Needs review
	ISLEOFGIANTS = "Isle of Giants", -- Requires localization
	ISLEOFQUELDANAS = "???????",
	ISLEOFTHUNDER = "Isle of Thunder", -- Requires localization
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "????", -- Needs review
	KALIMDOR = "???",
	KARAZHAN = "???", -- Needs review
	KELPTHARFOREST = "??????",
	KEZAN = "??",
	KHAZMODAN = "Khaz Modan", -- Requires localization
	KRASARANGWILDS = "?????",
	KUNLAISUMMIT = "???",
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "??", -- Needs review
	LEGENDARY = "??", -- Needs review
	LOCHMODAN = "????",
	LORDAERON = "Lordaeron", -- Requires localization
	LOSTCITYOFTHETOLVIR = "????????", -- Needs review
	LOVEISINTHEAIR = "?????", -- Needs review
	LUNARFESTIVAL = "????", -- Needs review
	MAGE = "??", -- Needs review
	MAGISTERSTERRACE = "?????", -- Needs review
	MAGTHERIDONSLAIR = "???????", -- Needs review
	MANATOMBS = "????", -- Needs review
	MAPFILTERS = "?????", -- Needs review
	MARAUDON = "???", -- Needs review
	MIDSUMMERFIREFESTIVAL = "?????", -- Needs review
	MINING = "??", -- Needs review
	MISCELLANEOUS = "??", -- Needs review
	MOGUSHANPALACE = "Mogu'shan Palace", -- Requires localization
	MOGUSHANVAULTS = "?????",
	MOLTENCORE = "????", -- Needs review
	MOLTENFRONT = "????",
	MONK = "??", -- Needs review
	MOONGLADE = "????",
	MOUNTHYJAL = "????",
	MULGORE = "???",
	NAGRAND = "???",
	NAXXRAMAS = "?????", -- Needs review
	NETHERSTORM = "????",
	NEWYEARSEVE = "???", -- Needs review
	NOBLEGARDEN = "????", -- Needs review
	NORTHERNBARRENS = "?????",
	NORTHERNKALIMDOR = "Northern Kalimdor", -- Requires localization
	NORTHERNSTRANGLETHORN = "????",
	NORTHREND = "???",
	OLDHILLSBRADFOOTHILLS = "??????????", -- Needs review
	ONYXIASLAIR = "????????", -- Needs review
	OPTIONS = "??", -- Needs review
	ORGRIMMAR = "???",
	OUTLAND = "??",
	PALACEOFTHEHEAVENS = "????", -- Needs review
	PALADIN = "???", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "????",
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "????????...", -- Needs review
	PILGRIMSBOUNTY = "?????", -- Needs review
	PITOFSARON = "????", -- Needs review
	PRIEST = "??", -- Needs review
	PROFESSIONS = "??", -- Needs review
	PROVINGGROUNDS = "Proving Grounds", -- Requires localization
	QUERYREQUESTED = "?????????????...", -- Needs review
	QUESTLISTFILTERS = "???????", -- Needs review
	QUESTSFOUND = "??? %d ???", -- Needs review
	RAGEFIRECHASM = "????", -- Needs review
	RAIDS = "??", -- Needs review
	RAZORFENDOWNS = "????", -- Needs review
	RAZORFENKRAUL = "????", -- Needs review
	REDRIDGEMOUNTAINS = "???",
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "??", -- Needs review
	RUINSOFAHNQIRAJ = "?????", -- Needs review
	RUINSOFGILNEAS = "??????",
	RUINSOFGILNEASCITY = "???????",
	SCARLETHALLS = "Scarlet Halls", -- Requires localization
	SCARLETMONASTERY = "?????", -- Needs review
	SCENARIO = "Scenario", -- Requires localization
	SCHOLOMANCE = "????", -- Needs review
	SEARINGGORGE = "????", -- Needs review
	SEASONAL = "???", -- Needs review
	SERPENTSHRINECAVERN = "??????", -- Needs review
	SETHEKKHALLS = "?????", -- Needs review
	SHADOPANMONASTERY = "????", -- Needs review
	SHADOWFANGKEEP = "????", -- Needs review
	SHADOWLABYRINTH = "????", -- Needs review
	SHADOWMOONBURIALGROUNDS = "Shadowmoon Burial Grounds", -- Requires localization
	SHADOWMOONVALLEY = "???", -- Needs review
	SHAMAN = "??", -- Needs review
	SHATTRATHCITY = "????", -- Needs review
	SHIMMERINGEXPANSE = "????", -- Needs review
	SHOLAZARBASIN = "?????", -- Needs review
	SHOWMAPICONS = "???????", -- Needs review
	SIEGEOFNIUZAOTEMPLE = "?????", -- Needs review
	SIEGEOFORGRIMMAR = "Siege of Orgrimmar", -- Requires localization
	SILITHUS = "????",
	SILVERMOONCITY = "???", -- Needs review
	SILVERPINEFOREST = "????", -- Needs review
	SILVERSHARDMINES = "????", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "??", -- Needs review
	SKYREACH = "Skyreach", -- Requires localization
	SORTALPHA = "????????", -- Needs review
	SORTLEVEL = "??????", -- Needs review
	SOUTHERNBARRENS = "?????",
	SOUTHERNKALIMDOR = "Southern Kalimdor", -- Requires localization
	SPECIAL = "??", -- Needs review
	SPECIALS = "??", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	SPIRESOFARAK = "Spires Of Arak", -- Requires localization
	STONETALONMOUNTAINS = "????",
	STORMSHIELD = "Stormshield", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STORMSTOUTBREWERY = "??????", -- Needs review
	STORMWINDCITY = "???", -- Needs review
	STRANDOFTHEANCIENTS = "????", -- Needs review
	STRANGLETHORNVALE = "???", -- Needs review
	STRATHOLME = "????", -- Needs review
	SUNKENTEMPLE = "?????", -- Needs review
	SUNSTRIDERISLE = "Sunstrider Isle", -- Requires localization
	SUNWELLPLATEAU = "??????", -- Needs review
	SWAMPOFSORROWS = "????", -- Needs review
	TAILORING = "??", -- Needs review
	TALADOR = "Talador", -- Requires localization
	TANAANJUNGLE = "Tanaan Jungle", -- Requires localization
	TANARIS = "????",
	TELDRASSIL = "????",
	TEMPESTKEEP = "????", -- Needs review
	TEMPLEOFAHNQIRAJ = "?????", -- Needs review
	TEMPLEOFKOTMOGU = "??????", -- Needs review
	TEMPLEOFTHEJADESERPENT = "Temple of the Jade Serpent", -- Requires localization
	TEMPLEOFTHEREDCRANE = "???", -- Needs review
	TEROKKARFOREST = "?????", -- Needs review
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEARCATRAZ = "????", -- Needs review
	THEBASTIONOFTWILIGHT = "????", -- Needs review
	THEBATTLEFORGILNEAS = "??????", -- Needs review
	THEBLACKMORASS = "??????", -- Needs review
	THEBLOODFURNACE = "???", -- Needs review
	THEBOTANICA = ":????", -- Needs review
	THECAPEOFSTRANGLETHORN = "?????", -- Needs review
	THECULLINGOFSTRATHOLME = "???????", -- Needs review
	THEDEADMINES = "????", -- Needs review
	THEEVERBLOOM = "The Everbloom", -- Requires localization
	THEEXODAR = "????",
	THEEYE = "????", -- Needs review
	THEEYEOFETERNITY = "????", -- Needs review
	THEFORGEOFSOULS = "????", -- Needs review
	THEGATEOFTHESETTINGSUN = "????", -- Needs review
	THEHALFHILLMARKET = "????", -- Needs review
	THEHINTERLANDS = "???", -- Needs review
	THEJADEFOREST = "???", -- Needs review
	THELOSTISLES = "????", -- Needs review
	THEMAELSTROM = "???", -- Needs review
	THEMECHANAR = "????", -- Needs review
	THENEXUS = "????", -- Needs review
	THEOBSIDIANSANCTUM = "????", -- Needs review
	THEOCULUS = "????", -- Needs review
	THERUBYSANCTUM = "????", -- Needs review
	THESHATTEREDHALLS = "????", -- Needs review
	THESLAVEPENS = "????", -- Needs review
	THESTEAMVAULT = "????", -- Needs review
	THESTOCKADE = "??", -- Needs review
	THESTONECORE = "????", -- Needs review
	THESTORMPEAKS = "????", -- Needs review
	THETEMPLEOFTHEJADESERPENT = "???", -- Needs review
	THEUNDERBOG = "????", -- Needs review
	THEVEILEDSTAIR = "?????", -- Needs review
	THEVIOLETHOLD = "????", -- Needs review
	THEVORTEXPINNACLE = "????", -- Needs review
	THEWANDERINGISLE = "???", -- Needs review
	THEZANDALARI = "???", -- Needs review
	THOUSANDNEEDLES = "????",
	THRONEOFTHEFOURWINDS = "????", -- Needs review
	THRONEOFTHETIDES = "????", -- Needs review
	THRONEOFTHUNDER = "Throne of Thunder", -- Requires localization
	THUNDERBLUFF = "???",
	TIMELESSISLE = "Timeless Isle", -- Requires localization
	TIRISFALGLADES = "??????", -- Needs review
	TOLBARAD = "????", -- Needs review
	TOLBARADPENINSULA = "??????", -- Needs review
	TOURNAMENT = "?????", -- Needs review
	TOWNLONGSTEPPES = "????", -- Needs review
	TRIALOFTHECHAMPION = "????", -- Needs review
	TRIALOFTHECRUSADER = "?????", -- Needs review
	TWILIGHTHIGHLANDS = "????", -- Needs review
	TWINPEAKS = "???", -- Needs review
	ULDAMAN = "???", -- Needs review
	ULDUAR = "???", -- Needs review
	ULDUM = "???",
	UNDERCITY = "???", -- Needs review
	UNGAINGOO = "Unga Ingoo", -- Requires localization
	UNGOROCRATER = "??????",
	UPPERBLACKROCKSPIRE = "Upper Blackrock Spire", -- Requires localization
	UTGARDEKEEP = "??????", -- Needs review
	UTGARDEPINNACLE = "??????", -- Needs review
	VALEOFETERNALBLOSSOMS = "???", -- Needs review
	VALLEYOFTHEFOURWINDS = "???", -- Needs review
	VASHJIR = "????", -- Needs review
	VAULTOFARCHAVON = "?????", -- Needs review
	WAILINGCAVERNS = "????", -- Needs review
	WARLOCK = "??", -- Needs review
	WARRIOR = "??", -- Needs review
	WARSONGGULCH = "????", -- Needs review
	WARSPEAR = "Warspear", -- Requires localization
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WELLOFETERNITY = "????", -- Needs review
	WESTERNPLAGUELANDS = "?????", -- Needs review
	WESTFALL = "????", -- Needs review
	WETLANDS = "??", -- Needs review
	WINTERGRASP = "???", -- Needs review
	WINTERSPRING = "???",
	WINTERVEIL = "???", -- Needs review
	WORLDEVENTS = "????", -- Needs review
	ZANGARMARSH = "????", -- Needs review
	ZULAMAN = "???", -- Needs review
	ZULDRAK = "?????", -- Needs review
	ZULFARRAK = "?????", -- Needs review
	ZULGURUB = "?????", -- Needs review
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "The Dreamgrove",
	AZSUNA = "Azsuna",
	HIGHMOUNTAIN = "Highmountain",
	STORMHEIM = "Stormheim",
	SURAMAR = "Suramar",
	VALSHARAH = "Val'sharah",
	DEMONHUNTER = "Demon Hunter",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Hall of the Guardian",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Netherlight Temple",
	SKYHOLD = "Skyhold",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	ACHERUSTHEEBONHOLD = "Acherus: The Ebon Hold",
	BLACKOOKHOLD = "Black Rook Hold",
	COURTOFSTARS = "Court of Stars",
	DARKHEARTTHICKET	 = "Darkheart Thicket",
	EYEOFAZSHARA = "	Eye of Azshara",
	HALLSOFVALOR = "Halls of Valor",
	MAWOFSOULS = "Maw of Souls",
	NELTHARIONSLAIR = "Neltharion's Lair",
	THEARCWAY = "The Arcway", 
	VAULTOFTHEWARDENS = "Vault of the Wardens",
	VIOLETHOLD = "Violet Hold",
	THEEMERALDNIGHTMARE = "The Emerald Nightmare",
	TRIALOFVALOR = "Trial of Valor",
	THENIGHTHOLD = "	The Nighthold",
	BROKENSHORE = "Broken Shore",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	CATHEDRALOFETERNALNIGHT = "Cathedral of Eternal Night", 
	RETURNTOKARAZHAN = "Return to Karazhan",
 	TOMBOFSARGERAS = "Tomb of Sargeras",
}

end