if GetLocale() == "zhCN" then
qcLocalize = {
	ABYSSALDEPTHS = "Abyssal Depths", -- Requires localization
	AHNKAHETTHEOLDKINGDOM = "Ahn'kahet: The Old Kingdom", -- Requires localization
	AHNQIRAJ = "???", -- Needs review
	AHNQIRAJTHEFALLENKINGDOM = "?????????", -- Needs review
	ALCHEMY = "???", -- Needs review
	ALTERACVALLEY = "Alterac Valley", -- Requires localization
	ARATHIBASIN = "Arathi Basin", -- Requires localization
	ARATHIHIGHLANDS = "?????", -- Needs review
	ARCHAEOLOGY = "Archaeology", -- Requires localization
	ASHENVALE = "??", -- Needs review
	ASHRAN = "Ashran", -- Requires localization
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AUCHENAICRYPTS = "Auchenai Crypts", -- Requires localization
	AUCHINDOUN = "Auchindoun", -- Requires localization
	AZEROTH = "Azeroth", -- Requires localization
	AZJOLNERUB = "Azjol-Nerub", -- Requires localization
	AZSHARA = "???", -- Needs review
	AZUREMYSTISLE = "???", -- Needs review
	BADLANDS = "????", -- Needs review
	BARADINHOLD = "Baradin Hold", -- Requires localization
	BATTLEGROUNDS = "Battlegrounds", -- Requires localization
	BATTLEPETS = "????", -- Needs review
	BLACKFATHOMDEEPS = "Blackfathom Deeps", -- Requires localization
	BLACKROCKCAVERNS = "Blackrock Caverns", -- Requires localization
	BLACKROCKDEPTHS = "Blackrock Depths", -- Requires localization
	BLACKROCKFOUNDRY = "Blackrock Foundry", -- Requires localization
	BLACKROCKSPIRE = "Blackrock Spire", -- Requires localization
	BLACKSMITHING = "Blacksmithing", -- Requires localization
	BLACKTEMPLE = "Black Temple", -- Requires localization
	BLACKWINGDESCENT = "Blackwing Descent", -- Requires localization
	BLACKWINGLAIR = "Blackwing Lair", -- Requires localization
	BLADESEDGEMOUNTAINS = "???", -- Needs review
	BLASTEDLANDS = "????", -- Needs review
	BLOODMAULSLAGMINES = "Bloodmaul Slag Mines", -- Requires localization
	BLOODMYSTISLE = "???", -- Needs review
	BOREANTUNDRA = "????", -- Needs review
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "Brewfest", -- Requires localization
	BREWMOONFESTIVAL = "Brewmoon Festival", -- Requires localization
	BURNINGSTEPPES = "Burning Steppes", -- Requires localization
	CAVERNSOFTIME = "Caverns of Time", -- Requires localization
	CENTRALKALIMDOR = "Central Kalimdor", -- Requires localization
	CHILDRENSWEEK = "Children's Week", -- Requires localization
	CLASSES = "Classes", -- Requires localization
	CLASSQUESTS = "Class Quests", -- Requires localization
	CLEARUPDATECACHE = "Clear Update Cache...", -- Requires localization
	COILFANGRESERVOIR = "Coilfang Reservoir", -- Requires localization
	COMBINEDMAPANDQUESTFILTERS = "Combined Map & Quest List Filters", -- Requires localization
	CONFIGSUBTITLE = "These options allow you to change the way that Quest Completist handles and filters its data.", -- Requires localization
	CONFIGTITLE = "Quest Completist - Configuration", -- Requires localization
	CONTINENTS = "Continents", -- Requires localization
	COOKING = "Cooking", -- Requires localization
	CRYSTALSONGFOREST = "????", -- Needs review
	DALARAN = "???", -- Needs review
	DARKMOONFAIRE = "Darkmoon Faire", -- Requires localization
	DARKSHORE = "???", -- Needs review
	DARNASSUS = "????", -- Needs review
	DAYOFTHEDEAD = "Day of the Dead", -- Requires localization
	DEADWINDPASS = "????", -- Needs review
	DEATHKNIGHT = "Death Knight", -- Requires localization
	DEEPHOLM = "????", -- Needs review
	DEEPRUNTRAM = "Deeprun Tram", -- Requires localization
	DESOLACE = "????", -- Needs review
	DIREMAUL = "Dire Maul", -- Requires localization
	DRAENOR = "Draenor", -- Requires localization
	DRAGONBLIGHT = "????", -- Needs review
	DRAGONSOUL = "????", -- Needs review
	DRAKTHARONKEEP = "Drak'Tharon Keep", -- Requires localization
	DREADWASTES = "Dread Wastes", -- Requires localization
	DRUID = "Druid", -- Requires localization
	DUNGEONSANDRAIDS = "Dungeons & Raids", -- Requires localization
	DUNMOROGH = "???", -- Needs review
	DUROTAR = "????", -- Needs review
	DUSKWOOD = "Duskwood", -- Requires localization
	DUSTWALLOWMARSH = "????", -- Needs review
	EASTERNKINGDOMS = "????", -- Needs review
	EASTERNPLAGUELANDS = "?????", -- Needs review
	ELEMENTALBONDS = "Elemental Bonds", -- Requires localization
	ELWYNNFOREST = "?????", -- Needs review
	ENCHANTING = "??", -- Needs review
	ENDTIME = "End Time", -- Requires localization
	ENGINEERING = "???", -- Needs review
	EVERSONGWOODS = "????", -- Needs review
	EYEOFTHESTORM = "????", -- Needs review
	FELWOOD = "?????", -- Needs review
	FERALAS = "???", -- Needs review
	FIRELANDS = "Firelands", -- Requires localization
	FIRELANDSINVASION = "Firelands Invasion", -- Requires localization
	FIRSTAID = "??", -- Needs review
	FISHING = "??", -- Needs review
	FROSTFIRERIDGE = "Frostfire Ridge", -- Requires localization
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GATEOFTHESETTINGSUN = "Gate of the Setting Sun", -- Requires localization
	GHOSTLANDS = "????", -- Needs review
	GILNEAS = "????", -- Needs review
	GILNEASCITY = "?????", -- Needs review
	GNOMEREGAN = "Gnomeregan", -- Requires localization
	GORGROND = "Gorgrond", -- Requires localization
	GREENSTONEVILLAGE = "Greenstone Village", -- Requires localization
	GRIMBATOL = "Grim Batol", -- Requires localization
	GRIMRAILDEPOT = "Grimrail Depot", -- Requires localization
	GRIZZLYHILLS = "Grizzly Hills", -- Requires localization
	GRUULSLAIR = "Gruul's Lair", -- Requires localization
	GUNDRAK = "Gundrak", -- Requires localization
	HALLOWSEND = "???", -- Needs review
	HALLSOFLIGHTNING = "Halls of Lightning", -- Requires localization
	HALLSOFORIGINATION = "Halls of Origination", -- Requires localization
	HALLSOFREFLECTION = "Halls of Reflection", -- Requires localization
	HALLSOFSTONE = "Halls of Stone", -- Requires localization
	HARVESTFESTIVAL = "???", -- Needs review
	HELLFIRECITADEL = "Hellfire Citadel", -- Requires localization
	HELLFIREPENINSULA = "?????", -- Needs review
	HELLFIRERAMPARTS = "Hellfire Ramparts", -- Requires localization
	HERBALISM = "???", -- Needs review
	HIDECOMPLETEDQUESTS = "Hide Completed Quests", -- Requires localization
	HIDEINPROGRESSQUESTS = "Hide In-Progress Quests", -- Requires localization
	HIDELOWLEVELQUESTS = "Hide Low Level Quests", -- Requires localization
	HIDENONACTIVESEASONALQUESTS = "Hide Non-Active Seasonal Quests", -- Requires localization
	HIDEOTHERFACTIONQUESTS = "Hide Other Faction Quests", -- Requires localization
	HIDEOTHERPROFESSIONQUESTS = "Hide Other Profession Quests", -- Requires localization
	HIDEOTHERRACEANDCLASSQUESTS = "Hide Other Race & Class Quests", -- Requires localization
	HIGHMAUL = "Highmaul", -- Requires localization
	HILLSBRADFOOTHILLS = "????????", -- Needs review
	HOUROFTWILIGHT = "Hour of Twilight", -- Requires localization
	HOWLINGFJORD = "????", -- Needs review
	HROTHGARSLANDING = "Hrothgar's Landing", -- Requires localization
	HUNTER = "Hunter", -- Requires localization
	HYJALSUMMIT = "?????", -- Needs review
	ICECROWN = "????", -- Needs review
	ICECROWNCITADEL = "????", -- Needs review
	INSCRIPTION = "Inscription", -- Requires localization
	IRONDOCKS = "Iron Docks", -- Requires localization
	IRONFORGE = "???", -- Needs review
	ISLEOFCONQUEST = "Isle of Conquest", -- Requires localization
	ISLEOFGIANTS = "Isle of Giants", -- Requires localization
	ISLEOFQUELDANAS = "??????", -- Needs review
	ISLEOFTHUNDER = "Isle of Thunder", -- Requires localization
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "????", -- Needs review
	KALIMDOR = "????", -- Needs review
	KARAZHAN = "???", -- Needs review
	KELPTHARFOREST = "Kelp'thar Forest", -- Requires localization
	KEZAN = "??", -- Needs review
	KHAZMODAN = "Khaz Modan", -- Requires localization
	KRASARANGWILDS = "Krasarang Wilds", -- Requires localization
	KUNLAISUMMIT = "Kun-Lai Summit", -- Requires localization
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "??", -- Needs review
	LEGENDARY = "Legendary", -- Requires localization
	LOCHMODAN = "????", -- Needs review
	LORDAERON = "Lordaeron", -- Requires localization
	LOSTCITYOFTHETOLVIR = "???????", -- Needs review
	LOVEISINTHEAIR = "Love is in the Air", -- Requires localization
	LUNARFESTIVAL = "??", -- Needs review
	MAGE = "??", -- Needs review
	MAGISTERSTERRACE = "Magisters' Terrace", -- Requires localization
	MAGTHERIDONSLAIR = "Magtheridon's Lair", -- Requires localization
	MANATOMBS = "????", -- Needs review
	MAPFILTERS = "Map Filters", -- Requires localization
	MARAUDON = "??????", -- Needs review
	MIDSUMMERFIREFESTIVAL = "???", -- Needs review
	MINING = "??", -- Needs review
	MISCELLANEOUS = "Miscellaneous", -- Requires localization
	MOGUSHANPALACE = "Mogu'shan Palace", -- Requires localization
	MOGUSHANVAULTS = "Mogu'shan Vaults", -- Requires localization
	MOLTENCORE = "Molten Core", -- Requires localization
	MOLTENFRONT = "????", -- Needs review
	MONK = "??", -- Needs review
	MOONGLADE = "????", -- Needs review
	MOUNTHYJAL = "????", -- Needs review
	MULGORE = "???", -- Needs review
	NAGRAND = "???", -- Needs review
	NAXXRAMAS = "Naxxramas", -- Requires localization
	NETHERSTORM = "????", -- Needs review
	NEWYEARSEVE = "New Year's Eve", -- Requires localization
	NOBLEGARDEN = "Noblegarden", -- Requires localization
	NORTHERNBARRENS = "?????", -- Needs review
	NORTHERNKALIMDOR = "Northern Kalimdor", -- Requires localization
	NORTHERNSTRANGLETHORN = "????", -- Needs review
	NORTHREND = "???", -- Needs review
	OLDHILLSBRADFOOTHILLS = "Old Hillsbrad Foothills", -- Requires localization
	ONYXIASLAIR = "Onyxia's Lair", -- Requires localization
	OPTIONS = "Options", -- Requires localization
	ORGRIMMAR = "????", -- Needs review
	OUTLAND = "??", -- Needs review
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "???", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "????", -- Needs review
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "Perform Server Query...", -- Requires localization
	PILGRIMSBOUNTY = "Pilgrim's Bounty", -- Requires localization
	PITOFSARON = "Pit of Saron", -- Requires localization
	PRIEST = "Priest", -- Requires localization
	PROFESSIONS = "Professions", -- Requires localization
	PROVINGGROUNDS = "Proving Grounds", -- Requires localization
	QUERYREQUESTED = "A server query has been requested...", -- Requires localization
	QUESTLISTFILTERS = "Quest List Filters", -- Requires localization
	QUESTSFOUND = "%d Quests Found", -- Requires localization
	RAGEFIRECHASM = "Ragefire Chasm", -- Requires localization
	RAIDS = "??", -- Needs review
	RAZORFENDOWNS = "Razorfen Downs", -- Requires localization
	RAZORFENKRAUL = "Razorfen Kraul", -- Requires localization
	REDRIDGEMOUNTAINS = "???", -- Needs review
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "???", -- Needs review
	RUINSOFAHNQIRAJ = "Ruins of Ahn'Qiraj", -- Requires localization
	RUINSOFGILNEAS = "??????", -- Needs review
	RUINSOFGILNEASCITY = "???????", -- Needs review
	SCARLETHALLS = "Scarlet Halls", -- Requires localization
	SCARLETMONASTERY = "Scarlet Monastery", -- Requires localization
	SCENARIO = "Scenario", -- Requires localization
	SCHOLOMANCE = "Scholomance", -- Requires localization
	SEARINGGORGE = "Searing Gorge", -- Requires localization
	SEASONAL = "??", -- Needs review
	SERPENTSHRINECAVERN = "Serpentshrine Cavern", -- Requires localization
	SETHEKKHALLS = "Sethekk Halls", -- Requires localization
	SHADOPANMONASTERY = "Shado-Pan Monastery", -- Requires localization
	SHADOWFANGKEEP = "Shadowfang Keep", -- Requires localization
	SHADOWLABYRINTH = "Shadow Labyrinth", -- Requires localization
	SHADOWMOONBURIALGROUNDS = "Shadowmoon Burial Grounds", -- Requires localization
	SHADOWMOONVALLEY = "???", -- Needs review
	SHAMAN = "????", -- Needs review
	SHATTRATHCITY = "????", -- Needs review
	SHIMMERINGEXPANSE = "Shimmering Expanse", -- Requires localization
	SHOLAZARBASIN = "?????", -- Needs review
	SHOWMAPICONS = "Show Map Icons", -- Requires localization
	SIEGEOFNIUZAOTEMPLE = "Siege of Niuzao Temple", -- Requires localization
	SIEGEOFORGRIMMAR = "Siege of Orgrimmar", -- Requires localization
	SILITHUS = "????", -- Needs review
	SILVERMOONCITY = "???", -- Needs review
	SILVERPINEFOREST = "????", -- Needs review
	SILVERSHARDMINES = "Silver Shard Mines", -- Requires localization
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "Skinning", -- Requires localization
	SKYREACH = "Skyreach", -- Requires localization
	SORTALPHA = "Sort: Alphabetically", -- Requires localization
	SORTLEVEL = "Sort: Level", -- Requires localization
	SOUTHERNBARRENS = "?????", -- Needs review
	SOUTHERNKALIMDOR = "Southern Kalimdor", -- Requires localization
	SPECIAL = "??", -- Needs review
	SPECIALS = "??", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	SPIRESOFARAK = "Spires Of Arak", -- Requires localization
	STONETALONMOUNTAINS = "????", -- Needs review
	STORMSHIELD = "Stormshield", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STORMSTOUTBREWERY = "Stormstout Brewery", -- Requires localization
	STORMWINDCITY = "???", -- Needs review
	STRANDOFTHEANCIENTS = "Strand of the Ancients", -- Requires localization
	STRANGLETHORNVALE = "Stranglethorn Vale", -- Requires localization
	STRATHOLME = "Stratholme", -- Requires localization
	SUNKENTEMPLE = "Sunken Temple", -- Requires localization
	SUNSTRIDERISLE = "Sunstrider Isle", -- Requires localization
	SUNWELLPLATEAU = "Sunwell Plateau", -- Requires localization
	SWAMPOFSORROWS = "????", -- Needs review
	TAILORING = "??", -- Needs review
	TALADOR = "Talador", -- Requires localization
	TANAANJUNGLE = "Tanaan Jungle", -- Requires localization
	TANARIS = "????", -- Needs review
	TELDRASSIL = "????", -- Needs review
	TEMPESTKEEP = "Tempest Keep", -- Requires localization
	TEMPLEOFAHNQIRAJ = "?????", -- Needs review
	TEMPLEOFKOTMOGU = "Temple of Kotmogu", -- Requires localization
	TEMPLEOFTHEJADESERPENT = "Temple of the Jade Serpent", -- Requires localization
	TEMPLEOFTHEREDCRANE = "????", -- Needs review
	TEROKKARFOREST = "?????", -- Needs review
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEARCATRAZ = "The Arcatraz", -- Requires localization
	THEBASTIONOFTWILIGHT = "The Bastion of Twilight", -- Requires localization
	THEBATTLEFORGILNEAS = "??????", -- Needs review
	THEBLACKMORASS = "The Black Morass", -- Requires localization
	THEBLOODFURNACE = "The Blood Furnace", -- Requires localization
	THEBOTANICA = "???", -- Needs review
	THECAPEOFSTRANGLETHORN = "The Cape of Stranglethorn", -- Requires localization
	THECULLINGOFSTRATHOLME = "The Culling of Stratholme", -- Requires localization
	THEDEADMINES = "????", -- Needs review
	THEEVERBLOOM = "The Everbloom", -- Requires localization
	THEEXODAR = "???", -- Needs review
	THEEYE = "The Eye", -- Requires localization
	THEEYEOFETERNITY = "????", -- Needs review
	THEFORGEOFSOULS = "The Forge of Souls", -- Requires localization
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHALFHILLMARKET = "The Halfhill Market", -- Requires localization
	THEHINTERLANDS = "The Hinterlands", -- Requires localization
	THEJADEFOREST = "????", -- Needs review
	THELOSTISLES = "???", -- Needs review
	THEMAELSTROM = "The Maelstrom", -- Requires localization
	THEMECHANAR = "The Mechanar", -- Requires localization
	THENEXUS = "?????", -- Needs review
	THEOBSIDIANSANCTUM = "The Obsidian Sanctum", -- Requires localization
	THEOCULUS = "The Oculus", -- Requires localization
	THERUBYSANCTUM = "?????", -- Needs review
	THESHATTEREDHALLS = "????", -- Needs review
	THESLAVEPENS = "????", -- Needs review
	THESTEAMVAULT = "The Steamvault", -- Requires localization
	THESTOCKADE = "The Stockade", -- Requires localization
	THESTONECORE = "????", -- Needs review
	THESTORMPEAKS = "????", -- Needs review
	THETEMPLEOFTHEJADESERPENT = "The Temple of the Jade Serpent", -- Requires localization
	THEUNDERBOG = "The Underbog", -- Requires localization
	THEVEILEDSTAIR = "The Veiled Stair", -- Requires localization
	THEVIOLETHOLD = "The Violet Hold", -- Requires localization
	THEVORTEXPINNACLE = "The Vortex Pinnacle", -- Requires localization
	THEWANDERINGISLE = "The Wandering Isle", -- Requires localization
	THEZANDALARI = "The Zandalari", -- Requires localization
	THOUSANDNEEDLES = "????", -- Needs review
	THRONEOFTHEFOURWINDS = "????", -- Needs review
	THRONEOFTHETIDES = "????", -- Needs review
	THRONEOFTHUNDER = "Throne of Thunder", -- Requires localization
	THUNDERBLUFF = "???", -- Needs review
	TIMELESSISLE = "Timeless Isle", -- Requires localization
	TIRISFALGLADES = "??????", -- Needs review
	TOLBARAD = "?????", -- Needs review
	TOLBARADPENINSULA = "???????", -- Needs review
	TOURNAMENT = "Tournament", -- Requires localization
	TOWNLONGSTEPPES = "Townlong Steppes", -- Requires localization
	TRIALOFTHECHAMPION = "?????", -- Needs review
	TRIALOFTHECRUSADER = "??????", -- Needs review
	TWILIGHTHIGHLANDS = "Twilight Highlands", -- Requires localization
	TWINPEAKS = "???", -- Needs review
	ULDAMAN = "???", -- Needs review
	ULDUAR = "???", -- Needs review
	ULDUM = "???", -- Needs review
	UNDERCITY = "???", -- Needs review
	UNGAINGOO = "Unga Ingoo", -- Requires localization
	UNGOROCRATER = "??????", -- Needs review
	UPPERBLACKROCKSPIRE = "Upper Blackrock Spire", -- Requires localization
	UTGARDEKEEP = "Utgarde Keep", -- Requires localization
	UTGARDEPINNACLE = "Utgarde Pinnacle", -- Requires localization
	VALEOFETERNALBLOSSOMS = "Vale of Eternal Blossoms", -- Requires localization
	VALLEYOFTHEFOURWINDS = "Valley of the Four Winds", -- Requires localization
	VASHJIR = "????", -- Needs review
	VAULTOFARCHAVON = "Vault of Archavon", -- Requires localization
	WAILINGCAVERNS = "Wailing Caverns", -- Requires localization
	WARLOCK = "Warlock", -- Requires localization
	WARRIOR = "Warrior", -- Requires localization
	WARSONGGULCH = "Warsong Gulch", -- Requires localization
	WARSPEAR = "Warspear", -- Requires localization
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WELLOFETERNITY = "Well of Eternity", -- Requires localization
	WESTERNPLAGUELANDS = "?????", -- Needs review
	WESTFALL = "Westfall", -- Requires localization
	WETLANDS = "??", -- Needs review
	WINTERGRASP = "???", -- Needs review
	WINTERSPRING = "???", -- Needs review
	WINTERVEIL = "Winter Veil", -- Requires localization
	WORLDEVENTS = "World Events", -- Requires localization
	ZANGARMARSH = "Zangarmarsh", -- Requires localization
	ZULAMAN = "???", -- Needs review
	ZULDRAK = "???", -- Needs review
	ZULFARRAK = "?????", -- Needs review
	ZULGURUB = "?????", -- Needs review
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "The Dreamgrove",
	AZSUNA = "Azsuna",
	HIGHMOUNTAIN = "Highmountain",
	STORMHEIM = "Stormheim",
	SURAMAR = "Suramar",
	VALSHARAH = "Val'sharah",
	DEMONHUNTER = "Demon Hunter",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Hall of the Guardian",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Netherlight Temple",
	SKYHOLD = "Skyhold",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	ACHERUSTHEEBONHOLD = "Acherus: The Ebon Hold",
	BLACKOOKHOLD = "Black Rook Hold",
	COURTOFSTARS = "Court of Stars",
	DARKHEARTTHICKET	 = "Darkheart Thicket",
	EYEOFAZSHARA = "	Eye of Azshara",
	HALLSOFVALOR = "Halls of Valor",
	MAWOFSOULS = "Maw of Souls",
	NELTHARIONSLAIR = "Neltharion's Lair",
	THEARCWAY = "The Arcway", 
	VAULTOFTHEWARDENS = "Vault of the Wardens",
	VIOLETHOLD = "Violet Hold",
	THEEMERALDNIGHTMARE = "The Emerald Nightmare",
	TRIALOFVALOR = "Trial of Valor",
	THENIGHTHOLD = "	The Nighthold",
	BROKENSHORE = "Broken Shore",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	CATHEDRALOFETERNALNIGHT = "Cathedral of Eternal Night", 
	RETURNTOKARAZHAN = "Return to Karazhan",
 	TOMBOFSARGERAS = "Tomb of Sargeras",
}

end